# Generated by Django 6.0.6 on 2026-06-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Предмет тестирования')),
            ],
            options={
                'verbose_name': 'Предмет тестирования',
                'verbose_name_plural': 'Предметы тестирования',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер билета')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='testing.category', verbose_name='Предмет тестирования')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['category', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TicketQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок вопроса в билете')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_questions', to='testing.question', verbose_name='Вопрос')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_questions', to='testing.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Вопрос в билете',
                'verbose_name_plural': 'Вопросы в билетах',
                'ordering': ['ticket', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('category', 'number'), name='unique_ticket_number_in_category'),
        ),
        migrations.AddConstraint(
            model_name='ticketquestion',
            constraint=models.UniqueConstraint(fields=('ticket', 'question'), name='unique_question_in_ticket'),
        ),
        migrations.AddConstraint(
            model_name='ticketquestion',
            constraint=models.UniqueConstraint(fields=('ticket', 'order'), name='unique_question_order_in_ticket'),
        ),
    ]
